### ISSUE TITLE
`str` object has no attribute 'select'

### ISSUE THREAD

**Issue by lovit** [lovit/naver_movie_scraper#3]
Found some exception from executing below script.

```
python scrap.py --directory ./output/ --begin_idx 134963 --end_idx 134963 --specific_idx '' --sleep 0.1 --casting --comments --bestscripts --debug
```

```
{'filename': '/Users/hyunjoongkim/git/naver_movie_scraper/naver_movie_scraper/utils.py',
 'lineno': 30,
 'message': "Couldn't find a tree builder with the features you requested: "
            'lxml. Do you need to install a parser library?',
 'name': 'get_soup',
 'type': 'FeatureNotFound'}
movie id = 134963
'str' object has no attribute 'select'
Exist 1 exceptions
```

**Comment by lovit** [comment]
has been resolved by [9adb636](https://github.com/lovit/naver_movie_scraper/commit/9adb636c670d6fe23067b17d8e5aeeda5a6e9230).

Install lxml and beautifulsoup4

```
pip install lxml beautifulsoup4
```

**Comment by lovit** [comment]
My test environment is 
- python 3.7.7
- beautifulsoup4==4.7.1 & 4.9.0
- lxml==4.5.0

**Comment by oxox97** [comment]
```python
from bs4 import BeautifulSoup    #html 관점에서 read
import pprint
import re
import sys
import requests
#from urllib.request import urlopen



normalize_pattern = re.compile('[\r\n\t]')
doublespcae_pattern = re.compile('[\s]+')


def get_soup(url, headers=None, allow_redirects=False):
    """
    Argument
    --------
    url : str
        Web page url
    headers : dict or None
        Headers
    allow_redirects : Boolean
    Returns
    -------
    bs4.Beautifulsoup format HTML page
    """

    try:
        r = requests.get(url, headers=headers, allow_redirects=allow_redirects).text
        return BeautifulSoup(r, 'lxml')
    except Exception as e:
        exc_type, exc_value, exc_traceback = sys.exc_info()
        traceback_details = {
            'filename': exc_traceback.tb_frame.f_code.co_filename,
            'lineno'  : exc_traceback.tb_lineno,
            'name'    : exc_traceback.tb_frame.f_code.co_name,
            'type'    : exc_type.__name__,
            'message' : str(e)
        }
        pprint(traceback_details)
        return ''




def meta_score(soup):
    try:
        main_score = soup.select('div[class=main_score]')[0]
        expert_score = main_score.select('div[class=spc_score_area] div[class=star_score]')[0].text.replace('\n','')
        netizen_score = main_score.select('div[class=star_score] span[class=st_off]')[0].text.replace('관람객 평점 ', '').replace('점', '')
        return float(expert_score), float(netizen_score)
    except Exception as e:
        print(e)
        return -1, -1



basic_url_form = 'http://movie.naver.com/movie/bi/mi/basic.nhn?code={}' # idx

def scrap_basic(idx):
    url = basic_url_form.format(idx)
    soup = get_soup(url)
    infomation = {
        'movie_idx': idx,
        'expert_score': meta_score(soup)[0],
        'netizen_score': meta_score(soup)[1],

    }
    return infomation




    
idx = 134963
res = (scrap_basic(idx))
print(res)

```


결과:

```
File "C:\Users\oxox9\.spyder-py3\Regression_crawling.py", line 50, in meta_score
    main_score = soup.select('div[class=main_score]')[0]

IndexError: list index out of range
```




메일 보낸 학생입니다. 코드를 이렇게 돌려보았는데, 
(저는 라라랜드에 대한 네티즌평점과 전문가평점을 크롤링 하고자 합니다.)
(def meta_score에서 try만 주석처리 하였습니다

meta score 함수를 실행할 때,  main_score 문에서 에러가 발생합니다.
제 생각에는 main_score 리스트에 값이 없어, [0]으로 index를 지정해도 에러가 난 것 같습니다.

어디가 잘못된 것일까요?

github에서 자료를 찾은게 처음이라 이렇게 올려도 되는지 잘 모르겠습니다. 죄송합니다.
알려주신다면 형식에 맞게 수정하겠습니다. 감사합니다.

**Comment by lovit** [comment]
index out of range 이니 아마 짐작하신 문제가 맞을것입니다. 하지만 동일한 스크립트를 제가 돌렸을 때에는 모두 정상작동 하였습니다.

1.
코드에 문제가 없어서 출력구문을 모두 지웠던건데, 아래처럼 exception 부분의 코드를 고쳐 실제 어떤 문제가 일어난건지 확인해 보실 수도 있습니다.

```python
def meta_score(soup):
    try:
        main_score = soup.select('div[class=main_score]')[0]
        expert_score = main_score.select('div[class=spc_score_area] div[class=star_score]')[0].text.replace('\n','')
        netizen_score = main_score.select('div[class=star_score] span[class=st_off]')[0].text.replace('관람객 평점 ', '').replace('점', '')
        return float(expert_score), float(netizen_score)
    except Exception as e:
        print(e)
        return -1, -1
```

혹은 조금 더 디테일하게 살펴보기 위하여


```python
from pprint import pprint

def meta_score(soup):
    try:
        main_score = soup.select('div[class=main_score]')[0]
        expert_score = main_score.select('div[class=spc_score_area] div[class=star_score]')[0].text.replace('\n','')
        netizen_score = main_score.select('div[class=star_score] span[class=st_off]')[0].text.replace('관람객 평점 ', '').replace('점', '')
        return float(expert_score), float(netizen_score)
    except Exception as e:
        exc_type, exc_value, exc_traceback = sys.exc_info()
        traceback_details = {
            'filename': exc_traceback.tb_frame.f_code.co_filename,
            'lineno'  : exc_traceback.tb_lineno,
            'name'    : exc_traceback.tb_frame.f_code.co_name,
            'type'    : exc_type.__name__,
            'message' : str(e)
        }
        pprint(traceback_details)
        return -1, -1
```

2. 
beautifulsoup4 가 4.6, 4.7, 로 넘어오면서 select 함수에 몇 가지 변화가 있었고, 이 때문에 저도 몇 가지 코드를 고쳤던 기억이 있습니다. 패키지 버전을 확인해 보시기 바랍니다. 제가 실행했던 환경은 [위의 커멘트](https://github.com/lovit/naver_movie_scraper/issues/3#issuecomment-615763500)에 적어두었습니다.

**Comment by oxox97** [comment]
현재 
파이썬 : 3.7.6
lxml : 4.5.0
beautifulsoup4 : 4.8.2
(아나콘다 스파이더 사용 중)
버전인 것 같은데, 왜 계속 리스트 범위밖이라고 나오는지 정말 모르겠네욥..ㅠㅠㅠㅠㅠ
자세한 댓글은 정말 감사드립니다 (꾸벅)

**Comment by oxox97** [comment]
정말 감사드립니다.
 
 제 코드를 실행하셨을 때, 제대로 구동 된다는 말씀이신거죠?
 
그렇다면 파이썬이나 beautiful soup4 에 대한 버전에 대한 문제일까요.
 
버전을 선생님과 동일하게 하여 컴파일 해보는게 방법일까요?
 
감사합니다.
 
 
-----Original Message-----

**Comment by lovit** [comment]
아 코드를 수정하셨군요. 저는 README 에 적어놓은 script 로만 테스트했습니다.

**Comment by lovit** [comment]
몇몇 페이지들이 redirection 이 되고 있는 것 같습니다. 해당 이슈는 [62e2600](https://github.com/lovit/naver_movie_scraper/commit/62e26000c5136697d04115580fb7b3f04e09554b) 에서 해결하였습니다. 위의 코드는 링크를 걸어둔 커밋처럼 코드를 수정하시던지, README 의 script 를 이용하여 데이터를 긁어오신 뒤, 필요한 정보한 이후에 선택해 쓰시면 될 듯 합니다.

**Comment by oxox97** [comment]
와 정말 감사합니다.
get_soup 함수에서 
```
allow_redirects=True
```
로 수정해주었더니 제대로 작동을 하는군요. 
정말 감사드립니다.

**Comment by oxox97** [comment]
한 가지만 더 여쭤봐도 될까요?

제가 코드를 이해한 바로는, def meta_score에서 '기자,평론가' 평점과 ' 관람객' 평점을
변수에 저장하고 있습니다.
하지만 많은 영화들이 (ex. 신세계 idx=91031) 관람객 평점은 없지만 
네티즌 평점은 가지고 있습니다.

따라서 "기자평론가 평점"과 "관람객 평점"이 아닌
"기자평론가 평점"과 "네티즌 평점"의 값을 크롤링 하려고 하는데,

netizen_score 변수의 HTML 주소값을 어떻게 수정해야 할까요?

**Comment by lovit** [comment]
> 한 가지만 더 여쭤봐도 될까요?
> 
> 제가 코드를 이해한 바로는, def meta_score에서 '기자,평론가' 평점과 ' 관람객' 평점을
> 변수에 저장하고 있습니다.
> 하지만 많은 영화들이 (ex. 신세계 idx=91031) 관람객 평점은 없지만
> 네티즌 평점은 가지고 있습니다.
> 
> 따라서 "기자평론가 평점"과 "관람객 평점"이 아닌
> "기자평론가 평점"과 "네티즌 평점"의 값을 크롤링 하려고 하는데,
> 
> netizen_score 변수의 HTML 주소값을 어떻게 수정해야 할까요?

이 부분은 @oxox97 님의 작업이시니, 직접 공부하시면서 해결해야 하지 않을까요? 

`beautifulsoup4 select` 로 구글링해보면 필요한 자료들이 나올겁니다. 한 가지 [링크](https://dataitgirls2.github.io/tutorial/Tutorial_180719_BeautifulSoup.html)를 걸어두겠습니다.

**Comment by oxox97** [comment]
넵 마지막 질문은 제가 너무 철이 없었네요 죄송합니다.
 
제가 더 찾아보고 공부해 보겠습니다.
 
좋은 코드 공유해주셔서 정말 감사합니다.
 
앞으로도 github 많이 이용하며 , 저도 다른 사람들께 코드를 공유하는 위치까지 빨리 올라가고싶네요 ㅎㅎ
 
많은 도움되었습니다. 감사합니다!
 
-----Original Message-----

**Comment by lovit** [comment]
> 넵 마지막 질문은 제가 너무 철이 없었네요 죄송합니다. 제가 더 찾아보고 공부해 보겠습니다. 좋은 코드 공유해주셔서 정말 감사합니다. 앞으로도 github 많이 이용하며 , 저도 다른 사람들께 코드를 공유하는 위치까지 빨리 올라가고싶네요 ㅎㅎ 많은 도움되었습니다. 감사합니다!
> […](#)
> -----Original Message----- From: "Hyunjoong Kim"<notifications@github.com> To: "lovit/naver_movie_scraper"<naver_movie_scraper@noreply.github.com>; Cc: "oxox97"<oxox97@naver.com>; "Mention"<mention@noreply.github.com>; Sent: 2020-04-20 (월) 02:46:18 (GMT+09:00) Subject: Re: [lovit/naver_movie_scraper] `str` object has no attribute 'select' (#3) 한 가지만 더 여쭤봐도 될까요? 제가 코드를 이해한 바로는, def meta_score에서 '기자,평론가' 평점과 ' 관람객' 평점을 변수에 저장하고 있습니다. 하지만 많은 영화들이 (ex. 신세계 idx=91031) 관람객 평점은 없지만 네티즌 평점은 가지고 있습니다. 따라서 "기자평론가 평점"과 "관람객 평점"이 아닌 "기자평론가 평점"과 "네티즌 평점"의 값을 크롤링 하려고 하는데, netizen_score 변수의 HTML 주소값을 어떻게 수정해야 할까요? 이 부분은 @oxox97 님의 작업이시니, 직접 공부하시면서 해결해야 하지 않을까요? beautifulsoup4 select 로 구글링해보면 필요한 자료들이 나올겁니다. 한 가지 링크를 걸어두겠습니다. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

아니에요. 죄송할거 없습니다. 저도 정중하게 답변 드린거에요. 적극적으로 질문도 하시고 탐색도 하시니 꼭 그러실거라 생각합니다. 감사합니다.
