### ISSUE TITLE
Cli 변경 관련

### ISSUE THREAD

**Issue by ByungjunKim** [lovit/naver_movie_scraper#5]
안녕하세요 naver_movie_scraper 를 애용중인 연구자입니다.
오늘 들어와보니 작년말 업데이트로 cli가 변경되었네요.
기존에는 scrap.py 를 실행해 cli로 수집을 했는데요.
이번에는 cli.py를 실행하면 되나요? 실행을 해도 진행이 안되서 문의 드립니다.

감사합니다.

**Comment by lovit** [comment]
잘 사용해주신다니 감사합니다. 
작년에 업데이트 하면서 현재 폴더 위치에 관계없이 실행 가능한 패키지 형식으로 CLI 를 변경하였습니다.
사용법을 README 의 맨 아래 수정해뒀는데, 보기 힘든듯 하여 1981bfc 에서 내용 수정하였으며,
해당 내용 포함하여 [release](https://github.com/lovit/naver_movie_scraper/releases/tag/1.0.0) 해두었습니다.

감사합니다.

**Comment by ByungjunKim** [comment]
정말 감사합니다. 제가 README 내용을 면밀히 안읽어봐서 생긴 문제였네요. 그럼에도 친절히 다시 알려주셔서 다시한번 감사합니다.
2020-1학기에도 이 패키지를 수업시간에 활용했는데 정말 좋은 반응이 있었고, 프로젝트도 잘 진행할 수 있었습니다.
이번학기 수업에도 또 활용할 예정입니다. 좋은 패키지 널리널리 알리도록 하겠습니다.
